/** \file
 * CAN DBC C-Headers
 *
 * These headers were generated by dbc2c.awk on <:date:>.
 *
 * The dbc2c.awk script parses Vector .dbc files, and generates C-style
 * headers with Doxygen documentation from a set of templates.
 *
 * The following databases were parsed:
 * - \ref DB_<:db:>
 */

